# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               'blkdrops'
tagline:             'tech, art, and more'
description:         '© Copyright Brian Keppinger 2016.'
url:                 http://blkdrops.com
baseurl:             ''
paginate:            5
paginate_path:      "page:num"
excerpt_separator: <!--more-->

# Comments
comments: true
disqus:
  shortname: blkdrops

# Categories
permalink: /:categories/:title/

# Google services
google_analytics: UA-91364027-1
# About/contact
author:
  name:              Brian Keppinger
  url:
  email:             brian.keppinger@gmail.com

github_username: dangerrangerous
linkedin_username: briankeppinger
#vimeo_username:
instagram_username: briankeppinger

# Custom vars
version:             1.0.0

gems:
    - jekyll-paginate
    - jekyll-gist
