# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               'blkdrops'
tagline:             'technical knowledge and more'
description:         'Projects, tutorials, and musings. By Brian Keppinger'
url:                 http://blkdrops.com
baseurl:             ''
paginate:            5
paginate_path:      "page:num"

# Comments
comments: false
disqus:
  shortname: blkdrops

# About/contact
author:
  name:              Brian Keppinger
  url:
  email:             brian.keppinger@gmail.com

# Custom vars
version:             1.0.0

gems:
    - jekyll-paginate
    - jekyll-gist
